name: test

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Echo test
        run: echo "triggered after action on first repo - ${{github.event.client_payload.message}}"